### PR TITLE
moved core submodule to tip of REL1_27 to include 1.27.4 release

### PR DESCRIPTION
**Pull request by danielhartnell**
This should address https://bugzilla.mozilla.org/show_bug.cgi?id=1417097 and update MediaWiki core to the 1.27.4 release.

### CODE REVIEW

**Comment by danielhartnell** [comment]
Just to be somewhat verbose here, I did the following for this update:

1. `git submodule update --init core`
2. From `core/`, I checked out REL1_27 which now includes the 1.27.4 release
3. Created this PR

Once it's merged, I'll run through our UAT checklist to make sure everything functions in stage.

**Comment by danielhartnell** [comment]
Hey @tinnightcap,

Sorry for the slow response here. We are currently on 1.27.3 and here are some links to save you a search:

https://www.mediawiki.org/wiki/Release_notes/1.27#Changes_since_1.27.3
https://wiki.mozilla.org/Special:Version

I did attempt to test in the nubis-training account but I ran into some errors. It was a week ago so I don't have the exact errors on hand. I'll test it out again and follow up with you if I can't make it work.

**Comment by gozer** [comment]
That's makes it an update to some random point on the REL1_27 branch

The actual commit you are looking for is the tagged 1.27.4 release, no? 

wikimedia/mediawiki@a8064762ac3ff40d94c451a243f6c0e91a932e26
i.e.
https://github.com/wikimedia/mediawiki/releases/tag/1.27.4

**Comment by danielhartnell** [comment]
@gozer,

I've been digging through my memory banks and I'm not sure why that random point on the `REL1_27` branch was selected. Our `core` submodule points to `gerrit.wikimedia.org/r/p/mediawiki/core.git` but what you referenced above is just a mirror so your point stands (seeing `a8064762ac` in the snippet below).

Looks like I managed to delete the fork I had here so I'll see what I need to do to fix that and get the PR updated (or submit a new one). Looks like I can use this as an opportunity to try out jd's fancy new Nubis CLI stuff to deploy to the training account.

I'll follow up soon with something we can merge.

```
❯ git checkout 1.27.4
Note: checking out '1.27.4'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at a8064762ac... Bump 1.27.4

core git/1.27.4
❯ git remote -v
origin	https://gerrit.wikimedia.org/r/p/mediawiki/core.git (fetch)
origin	https://gerrit.wikimedia.org/r/p/mediawiki/core.git (push)
```

**Comment by tinnightcap** [comment]
This was done in PR #76

**Pull request closed without merging**
